# Generated by Django 4.0.3 on 2022-05-16 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
