# Generated by Django 4.0.3 on 2022-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
