# Generated by Django 4.0.3 on 2022-05-16 03:49

import core.models
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entity_email_alter_entity_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=utils.OverwiteStorageSystem, upload_to=core.models.entity_logo_upload_loacation),
        ),
    ]
