# Generated by Django 4.0.3 on 2022-06-11 04:27

import core.models
from django.db import migrations
import django_resized.forms
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_department_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=-1, size=[200, 200], storage=utils.OverwiteStorageSystem, upload_to=core.models.entity_logo_upload_loacation),
        ),
    ]
