# Generated by Django 4.0.3 on 2022-04-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GovernmentBudgetPlan',
            new_name='DraftBudgetPlan',
        ),
    ]
