# Generated by Django 4.0.3 on 2022-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_governmentbudgetplan_draftbudgetplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaccount',
            name='closing_balance',
            field=models.BigIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subaccount',
            name='opening_balance',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='state',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='state',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN'),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='state',
            field=models.TextField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN'),
        ),
    ]
