# Generated by Django 4.0.3 on 2022-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_subaccount_closing_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingsettings',
            name='item',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='name',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
