# Generated by Django 4.0.3 on 2022-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_subaccount_closing_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsjournals',
            name='siblings',
            field=models.ManyToManyField(to='accounts.accountsjournals'),
        ),
    ]
