# Generated by Django 4.0.3 on 2022-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_budgetplan_name_draftbudgetplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetplan',
            name='identifier',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='budgetplan',
            name='name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='draftbudgetplan',
            name='identifier',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='draftbudgetplan',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
