# Generated by Django 4.0.3 on 2022-04-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionaction',
            name='comment',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
