# Generated by Django 4.0.3 on 2022-04-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_requisitionaction_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='comments',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_type',
            field=models.CharField(choices=[('WORKS', 'WORKS'), ('SUPPLIES', 'SUPPLIES'), ('SERVICES', 'SERVICES')], max_length=16),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('EDITING', 'EDITING'), ('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=64),
        ),
        migrations.AlterField(
            model_name='requisitionaction',
            name='action',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('SUBMITTED', 'SUBMITTED'), ('APPROVED', 'APRROVED'), ('REJECTED', 'REJECTED'), ('LPO CREATED', 'LPO CREATED'), ('RFQ CREATED', 'RFQ CREATED'), ('COMPLETED', 'COMPLETED')], max_length=64),
        ),
    ]
