# Generated by Django 4.0.3 on 2022-04-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_alter_requisitionitem_long_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='requisition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='procurement.requisition'),
            preserve_default=False,
        ),
    ]
