# Generated by Django 4.0.3 on 2022-04-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_requisitionitem_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('company', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='requisition',
            name='delivery_date_max',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='delivery_date_min',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='LocalPurchaseOrder',
        ),
        migrations.AddField(
            model_name='requestforquotation',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.vendor'),
        ),
    ]
