# Generated by Django 4.0.3 on 2022-04-16 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_remove_requisitionitem_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='comments',
            new_name='comment',
        ),
    ]
