# Generated by Django 4.0.3 on 2022-04-17 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='procurement.quotation'),
        ),
    ]
