# Generated by Django 4.0.3 on 2022-04-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0011_alter_requisition_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='quotation',
        ),
    ]
